# Generated by Django 3.2.4 on 2021-06-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('names', models.CharField(max_length=256)),
                ('contact', models.IntegerField(primary_key=True, serialize=False)),
                ('interests', models.CharField(max_length=256)),
            ],
        ),
    ]
